Sprint:
    type: object
    config:
        description: "A sprint"
        fields:
            id:
                builder: "Relay::GlobalId"
            name:
                type: String!
                description: "Sprint name"
            owner:
                type: User!
                description: "Sprint owner"
            started:
                type: Boolean!
                description: "Whether the sprint is started"
            startDate:
                type: DateTime
                description: "Start date of the sprint"
            issues:
                description: "Issues in this sprint"
                type: sprintIssuesConnection!
                argsBuilder: "Relay::Connection"
                resolve: '@=resolver("sprint_issues", [value, args])'
        interfaces: [Node]

sprintIssuesConnection:
    type: relay-connection
    config:
        nodeType: Issue!
        resolveNode: '@=value.node'
